# Generated by Django 5.1 on 2024-08-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity',
            new_name='quantity_avl',
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
